model:
  name: 'osnet_ain_x1_0'
  pretrained: True
  load_weights1: 'log/training/osnet_x1_0_IVIS_Coustom_Dataset/model1/model.pth.tar-100'
  resume1: ''
  deploy: 'model1'

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip', 'random_erase', 'color_jitter']
  save_dir: 'log/training/osnet_x1_0_IVIS_Coustom_Dataset/output'

loss:
  name: 'triplet'
  softmax:
    label_smooth: True
  triplet:
    margin: 0.3
    weight_t: 0.5
    weight_x: 1.
  dml:
    weight_ml: 1.

train:
  optim: 'amsgrad'
  lr: 0.0015
  max_epoch: 100
  batch_size: 64
  fixbase_epoch: 10
  open_layers: ['classifier']
  lr_scheduler: 'cosine'

test:
  batch_size: 1
  dist_metric: 'euclidean'
  normalize_feature: True
  evaluate: True
  eval_freq: 1
  rerank: True
  visrank: True
  visrank_topk: 10
  ranks: [1,2,3,4,5,6,7,8,9,10]